= Grails 3 Versioned Files plugin

== Introduction to the Grails 3 Versioned Files plugin

The Grails 3 Versioned Files plugin adds support to attach files to domain models. It was intially inspired by great attachmentable plugin which at the time was limited to grails 2.
Main difference is with this plugin you can attach files and manage their versions.

=== Supported operations:
* attach
* detach
* upload (brand new file or new version of existing one)
* move to trash
* empty trash
* group in buckets
* show
* download (if the version is not selected will be downloaded latest)
* find

== Installation

Add a dependency in `build.gradle`:

[source,java]
[subs="attributes"]
----
dependencies {
   ...
   compile 'tools.blocks:grails3-versioned-files-plugin:{project-version}'
   ...
----
You only need to set these properties in application.yml or application.groovy:

[source,java]
----
annexable:
    repositoryPath: /home/user_name/annexable_docs
    bucket: test
----

== Usage
To enable Annexable interface you have teo options, static property:
[source,groovy]
.`Book.groovy`
----
package com.mycompany

class Book {

   static annexable = true

   ....
}
----
or implement Anneable interface:
[source,groovy]
.`Book.groovy`
----
package com.mycompany

class Book implements Annexable {

   ....
}
----
From now you can use your domains as files container.

=== Annex domain model
Contains meta information about file like type, size, version or name.

=== AnnexableDomain domain model
Allows to link your domain models with files (annexes).

=== AnnexableControllerTrait
All controllers are enhanced by this trait. Methods added:

.Methods added to controllers classes
[cols="40,60"]
|====================
| *Method* | *Description*

| *findAnnex*
| Allows to find annexes by part of the name of file and bucket

| *uploadAnnex*
|Allows to upload file as new Annex object or new version of existing one

| *attachAnnex*
|Allows to attach existing Annex object to your domain object

| *detachAnnex*
|Allows to detach previously attached Annex from your domain object

| *showAnnex*
|Same as downloadAnnex method but with changed headers

| *downloadAnnex*
|Allows to download file (if not version is set then the latest one will be used)

|====================

=== AnnexableController
Contains same methods as this added by `AnnexableControllerTrait`. It can be used instead of enhanced controllers methods.

=== AnnexableService
Contains methods which operates on FileRepo helper class.

=== Tags library

== History

=== Versions:
* 0.1.0 - first release with complete set of methods, controller enhance trait, service and files operations helper.